#!/bin/bash
# Railway 配置脚本 - 手动执行

echo "=== Railway 配置指南 ==="
echo ""
echo "请在 Railway 控制台手动添加以下环境变量："
echo ""
echo "1. 打开项目页面："
echo "   https://railway.com/project/5e1c61e5-8994-465c-ae6a-7ad52501206f/service/fee2b7f1-a3e5-4383-a7d2-c633fd4c83e9"
echo ""
echo "2. 点击 'Variables' 标签"
echo ""
echo "3. 添加以下环境变量："
echo ""
echo "   DATABASE_URL=postgresql://neondb_owner:npg_FjNWRTQ2gl1o@ep-raspy-mode-amvgg8he-pooler.c-5.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
echo ""
echo "   DASHSCOPE_API_KEY=<你的 DashScope API Key>"
echo ""
echo "   PORT=8000"
echo ""
echo "4. 点击 'Settings' 标签"
echo "   Root Directory 设置为：backend"
echo ""
echo "5. 返回 'Deployments' 标签，点击 'Deploy' 重新部署"
echo ""
echo "=== 完成 ==="
